

apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gen-policy-generator
policyDefaults:
  namespace: chewie-policies
  remediationAction: enforce
  placement:
    placementRuleName: "hub-only-chewie"

policies:
  - name: gen-policy
    remediationAction: enforce
    manifests:
      - path: namespace.yml

