apiVersion: v1
kind: ConfigMap
metadata:
  name: acm-ldap-ca-config
  namespace: openshift-config
data:
  ca.crt: |
    Test crt
  ca-hub.crt: |
    {{hub fromConfigMap "wookie-policies" "ldap-ca-config" "ca.crt" | autoindent  hub}}