

apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: amc-policy-generator
policyDefaults:
  namespace: wookie-policies
  remediationAction: enforce
  placement:
    placementRuleName: "hub-only"

policies:
  - name: ldap-ca-policy
    remediationAction: enforce
    manifests:
      - path: acm-ldap-ca-config.yml

