apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- hub-config/
- chewie/
- ldap-ca/

namespace: wookie-policies



commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous

