apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
# - acm-placements/
# - hub-config/
- chewie/
# - ldap-ca/
- gen-policy/
# - dynatrace/

# namespace: wookie-policies


commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous

