

apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gen-policy-generator
policyDefaults:
  namespace: wookie-policies
  remediationAction: enforce
  placement:
    placementRuleName: "hub-only"

policies:
  - name: noodles-policy
    remediationAction: enforce
    manifests:
      - path: namespace.yml
      - path: templates.yml

