---


apiVersion: v1
kind: Namespace
metadata:
  name: noodles
  labels:
    smbc-app: '{{ $clusterFullName:= "vst.bry.tamlab.rdu2.redhat.com" }}{{ $clusterFullName }}'
    smbc-name: '{{ $clusterFullName:= "vst.bry.tamlab.rdu2.redhat.com" }}{{ slice $clusterFullName 0 2 }}'
    smbc-until: '{{ range $i := (slice "vst.bry.tamlab.rdu2.redhat.com" 0 3) }}{{ $i }}{{ end }}'