---


apiVersion: v1
kind: Namespace
metadata:
  name: noodles
  labels:
    smbc-app: '{{ $clusterFullName:= "vst.bry.tamlab.rdu2.redhat.com" }}{{ $clusterFullName }}'
    smbc-name: '{{ $clusterFullName:= "vst.bry.tamlab.rdu2.redhat.com" }}{{ slice clusterFullName 1 2 }}'