---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-noodles
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-noodles-prod-ns
        spec:
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: noodles
          remediationAction: inform
          severity: low
  remediationAction: enforce