kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  # name: px-cluster- {{ fromClusterClaim "datacenter" }} - {{- if eq (fromClusterClaim "name") "local-cluster" -}} ocp103 {{- else -}} fromClusterClaim {{- end -}}
  # name: test12
  name: '{{- if eq (fromClusterClaim "name") "local-cluster" -}} ocp103 {{- else -}} fromClusterClaim {{- end -}}'
  namespace: portworx
  annotations:
    portworx.io/is-openshift: 'true'
    # set.name.full: 'px-cluster- {{- fromClusterClaim "datacenter" -}} - {{- if eq (fromClusterClaim "name") "local-cluster" -}} ocp103- {{- fromClusterClaim "name" }} {{- else -}} {{ fromClusterClaim "name" }} {{- end -}}'
spec:
  csi:
    enabled: true
  customImageRegistry: sonatypenxpr01.smbcgroup.com:18443/repository/portworx
  deleteStrategy:
    type: Uninstall
  image: portworx/oci-monitor:2.10.0
  imagePullPolicy: Always
  kvdb:
    internal: true
  monitoring:
    prometheus:
      exportMetrics: true
  placement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: px/enabled
            operator: NotIn
            values:
            - "false"
          - key: node-role.kubernetes.io/master
            operator: DoesNotExist
  revisionHistoryLimit: 10
  secretsProvider: k8s
  startPort: 17001
  storage:
    useAll: true
    kvdbDevice: /dev/sdc
  stork:
    enabled: true
    image: portworx/stork:2.9.0
    lockImage: true
    args:
      webhook-controller: "false"
      admin-namespace: portworx
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate