---
apiVersion: v1
data:
  apiToken: ZHQwYzAxLlAyS1FSRkZWTE00TkRXV0tQNTJWNUZSQi5QM0FWUDRaM05DN0pQQkZPNlRLNE5KSDVFS1ZBS0dISUlNUlE1RVFSWk4yWEhXR1BNUkNISTVCVVdOS0NLNVRN
  
kind: Secret
metadata:
  name: bry-tamlab
  namespace: dynatrace
type: Opaque