apiVersion: v1
kind: Service
metadata:
  annotations:
    metrics.dynatrace.com/port: "9979"
    metrics.dynatrace.com/scrape: "true"
    metrics.dynatrace.com/secure: "true"
    metrics.dynatrace.com/tls.ca.crt: configmap:openshift-config:etcd-metric-serving-ca:ca-bundle.crt
    metrics.dynatrace.com/tls.crt: secret:openshift-config:etcd-metric-client:tls.crt
    metrics.dynatrace.com/tls.key: secret:openshift-config:etcd-metric-client:tls.key
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
  labels:
    k8s-app: etcd
  name: etcd
  namespace: openshift-etcd
