

apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: dynatrace-operator
policyDefaults:
  namespace: wookie-policies
  remediationAction: enforce
policies:
  - name: dynatrace-operator
    manifests:
      - path: operatorgroup.yml
      - path: subscription.yml
      - path: api-secret.yml
      - path: dynakube.yml
      - path: namespace.yml
      - path: node-exporter-service.yml
