---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: dynatrace-operator
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: dynatrace-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
