---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: dynatrace-operator
  namespace: dynatrace
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: dynatrace-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  
  config:
    env:
      - name: DISABLE_DEFAULT_ARGOCD_INSTANCE
        value: true
        