apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd-cleaner
  namespace: clean-gitops
spec:
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 128Mi
    route:
      enabled: true
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: reencrypt
    service:
      type: ''
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  helpChatText: Cleaner Helper!!!
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: true
  initialSSHKnownHosts: {}
  rbac:
    defaultPolicy: readonly
    policy: |
      g, "smbc,ou-admins", role:admin
      p, role:org-team, projects, get, *, allow
      p, role:org-team, projects, create, *, allow
      p, role:org-team, projects, update, *, allow
      p, role:org-team, projects, delete, *, allow
      g, argoteam, role:org-team
    scopes: '[groups]'
  repo:
    resources:
      limits:
        cpu: '1'
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
  helpChatURL: 'https://coreos.slack.com/archives/CMP95ST2N'
  sso:
    dex:
      openShiftOAuth: true
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi
  ha:
    enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  kustomizeBuildOptions: '--enable-alpha-plugins'
  tls:
    ca: {}
  redis:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  controller:
    processors: {}
    resources:
      limits:
        cpu: '2'
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
    sharding: {}
